### ISSUE TITLE
Doesnt work 

### ISSUE THREAD

**Issue by eox** [ih1115/LichessBot#2]
Only works for the first move then stops working.

**Comment by ih1115** [comment]
I just fresh installed windows 10 and chrome with tamper monkey and it still works for me..

**Comment by eox** [comment]
oh i was just executing it in browser console. i dont use tamper monkey.

**Comment by eox** [comment]
wont work on on tpm either

https://i.imgur.com/tzjaPAy.gifv

**Comment by ih1115** [comment]
That's odd.. https://www.youtube.com/watch?v=FCp9dXF3rXQ

**Comment by eox** [comment]
works now with the tpm script i recopied it in.
